language: node_js
node_js:
  - '14'

branches:
  only:
    - main

script:
  - echo '******* Build starts *******'
  - echo 'Installing Dependencies'
  - npm install

# 코드 압축 후 s3 전송
before_deploy:
  - zip -r youtube-clone-web-service *
  - mkdir -p deploy
  - mv youtube-clone-web-service.zip deploy/youtube-clone-web-service.zip

# 압축된 파일 배포
deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: youtube-clone-artifact #s3 버킷
    region: ap-northeast-2
    skip_cleanup: true
    acl: private
    local_dir: deploy
    wait-until-deployed: true

  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: youtube-clone-artifact #s3 버킷
    key: youtube-clone-web-service.zip #S3 사용할 파일 지정
    bundle_type: zip
    application: youtube-clone-codedeploy #codedeploy 애플리케이션 이름
    deployment_group: youtube-clone-group #codedeploy group 배포 그룹 이름
    region: ap-northeast-2
    wait-until-deployed: true

notifications:
  email:
    recipients:
      - vanilaleedana@gmail.com
